import Head from "next/head";
import { useState, useEffect, useCallback } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [audioContext, setAudioContext] = useState(null);
  const [audioBuffer, setAudioBuffer] = useState(null);
  const [audio, setAudio] = useState(null);

  const ref = useCallback((node) => {
    if (node) {
      setAudio(node);
    }
  }, []);

  useEffect(() => {
    const audioContext = new AudioContext();
    setAudioContext(audioContext);

    const fetchAudio = async () => {
      const response = await fetch(`/Llama.mp3`);
      const arrayBuffer = await response.arrayBuffer();
      const audioBuffer = await audioContext.decodeAudioData(arrayBuffer);
      setAudioBuffer(audioBuffer);
    };
    fetchAudio();
  }, []);

  const playSound = () => {
    console.log("playSound", audio, audioContext);
    const source = audioContext.createBufferSource();
    source.connect(audioContext.destination);
    source.buffer = audioBuffer;
    source.start();
  };

  const stopSound = () => {
    audio.pause();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Galaxy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <audio src="/Llama.mp3" ref={ref} />
        <div onClick={() => playSound()}>holla</div>
      </main>
    </div>
  );
}
